### ISSUE TITLE
server start error

### ISSUE THREAD

**Issue by petruciorex** [EnderMediaDev/The-1.7.10-Pack#1023]
someone can help me with this error?
when i start the server this message appear's

C:\Users\usuario\Desktop\minecraft server>java -Xmx3G -Xms2G -XX:MaxPermSize=260
M -jar server.jar nogui
Error: Unable to access jarfile server.jar

C:\Users\usuario\Desktop\minecraft server>pause
Press any key to continue. . .

**Comment by xJon** [comment]
Why did you modify the LaunchServer.bat file?

**Comment by petruciorex** [comment]
I haven't,I just download accepted the EULA and started.

**Comment by xJon** [comment]
Then try to re-download.

**Comment by petruciorex** [comment]
i have re-instaled the java and redownloaded the files,but the same error appear

**Comment by onefreemanminecraft** [comment]
I encountered the same issue, I simply copied the contents of the launch server batch from 8.2 and updated the forge jar. here are the contents of my launch server batch you may need to update the ram:

@ECHO OFF

:: When setting the memory below make sure to include the amount of ram letter. M = MB, G = GB. Don't use 1GB for example, it's 1G ::

:: This is 64-bit memory ::
set memsixtyfour=10G

:: This is 32-bit memory - maximum 1.2G ish::
set memthirtytwo=1G

:: Don't edit past this point ::

if $SYSTEM_os_arch==x86 (
  echo OS is 32
  set mem=%memthirtytwo%
) else (
  echo OS is 64
  set mem=%memsixtyfour%
)
java -server -Xmx%mem% -XX:PermSize=256M -Dfml.queryResult=confirm -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui
PAUSE

**Comment by petruciorex** [comment]
I tryed but java run out of memory:


[02:15:20] [Server thread/ERROR]: Could not save crash report to .\crash-reports
\crash-2016-02-08_02.15.19-server.txt
java.lang.OutOfMemoryError: GC overhead limit exceeded
[02:15:20] [Server thread/ERROR]: We were unable to save this crash report to di
sk.
[02:15:20] [Server thread/WARN] [FML]: Can't revert to frozen GameData state wit
hout freezing first.
Exception in thread "Server thread" [02:15:22] [Server thread/INFO] [STDERR]: [j
ava.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundErro
r: cpw/mods/fml/common/event/FMLModIdMappingEvent$1
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.common.event.FMLModIdMappingEvent.<init>(FMLModI
dMappingEvent.java:39)
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.common.Loader.fireRemapEvent(Loader.java:984)
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.common.registry.GameData.revertToFrozen(GameData
.java:740)
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.common.Loader.serverStopped(Loader.java:849)
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.common.FMLCommonHandler.handleServerStopped(FMLC
ommonHandler.java:483)
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java
:489)
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.ja
va:685)
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.
event.FMLModIdMappingEvent$1
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(Launc
hClassLoader.java:191)
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at java.lang.ClassLoader.loadClass(Unknown Source)
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at java.lang.ClassLoader.loadClass(Unknown Source)
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  ... 7 more
[02:15:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]: Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by petruciorex** [comment]
so should be like this?

@ECHO OFF

set memsixtyfour=800M

set memthirtytwo=800M

if $SYSTEM_os_arch==x86 (
echo OS is 32
set mem=%memthirtytwo%
) else (
echo OS is 64
set mem=%memsixtyfour%
)
java -server -Xmx%mem% -XX:PermSize=256M -Dfml.queryResult=confirm -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui
PAUSE

**Comment by onefreemanminecraft** [comment]
That should be correct, at least it worked for me. If you have ram to spare I would suggest setting the 64bit memory to at least 3G.

**Comment by petruciorex** [comment]
thank you onefreemanminecraft, it worked corretly =D

**Comment by xJon** [comment]
:+1:
