### ISSUE TITLE
first time serv get work but crash and get Exception in thread "AE2 VersionChecker" 

### ISSUE THREAD

**Issue by jimmy06200** [EnderMediaDev/The-1.7.10-Pack#1046]
[17:20:24] [Server thread/INFO]: Starting minecraft server version 1.7.10
[17:21:08] [Server thread/INFO]: Loading properties
[17:21:08] [Server thread/INFO]: Default game type: SURVIVAL
[17:21:08] [Server thread/INFO]: Generating keypair
[17:21:08] [Server thread/INFO]: Starting Minecraft server on 64.74.111.78:25567
[17:21:38] [Server thread/WARN]: Failed to load user banlist: 
java.io.FileNotFoundException: banned-players.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_60]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_60]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_60]
	at com.google.common.io.Files.newReader(Files.java:86) ~[guava-17.0.jar:?]
	at net.minecraft.server.management.UserList.func_152679_g(SourceFile:124) ~[om.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.func_152620_y(SourceFile:99) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:25) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:21:38] [Server thread/WARN]: Failed to load ip banlist: 
java.io.FileNotFoundException: banned-ips.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_60]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_60]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_60]
	at com.google.common.io.Files.newReader(Files.java:86) ~[guava-17.0.jar:?]
	at net.minecraft.server.management.UserList.func_152679_g(SourceFile:124) ~[om.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.func_152619_x(SourceFile:91) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:27) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:21:38] [Server thread/WARN]: Failed to load operators list: 
java.io.FileNotFoundException: ops.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_60]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_60]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_60]
	at com.google.common.io.Files.newReader(Files.java:86) ~[guava-17.0.jar:?]
	at net.minecraft.server.management.UserList.func_152679_g(SourceFile:124) ~[om.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.func_72417_t(SourceFile:107) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:29) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:21:38] [Server thread/WARN]: Failed to load white-list: 
java.io.FileNotFoundException: whitelist.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_60]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_60]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_60]
	at com.google.common.io.Files.newReader(Files.java:86) ~[guava-17.0.jar:?]
	at net.minecraft.server.management.UserList.func_152679_g(SourceFile:124) ~[om.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.func_72418_v(SourceFile:123) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:30) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:21:38] [Server thread/INFO]: Preparing level "world"
[17:21:42] [Server thread/INFO]: Preparing start region for level 0
[17:21:43] [Server thread/INFO]: Preparing spawn area: 6%
[17:21:44] [Server thread/INFO]: Preparing spawn area: 15%
[17:21:45] [Server thread/INFO]: Preparing spawn area: 32%
[17:21:46] [Server thread/INFO]: Preparing spawn area: 47%
[17:21:47] [Server thread/INFO]: Preparing spawn area: 59%
[17:21:48] [Server thread/INFO]: Preparing spawn area: 69%
[17:21:49] [Server thread/INFO]: Preparing spawn area: 83%
[17:21:50] [Server thread/INFO]: Preparing spawn area: 97%
[17:21:50] [Server thread/INFO]: Done (11.665s)! For help, type "help" or "?"
[17:21:50] [Server thread/INFO]: Starting GS4 status listener
[17:21:50] [Query Listener #1/INFO]: Query running on 64.74.111.78:25567
[17:31:08] [Server thread/INFO]: Stopping the server
[17:31:08] [Server thread/INFO]: Stopping server
[17:31:08] [Server thread/INFO]: Saving players
[17:31:08] [Server thread/INFO]: Saving worlds
[17:31:08] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[17:31:09] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[17:31:09] [Server thread/INFO]: Saving chunks for level 'world'/The Last Millenium
[17:31:09] [Server thread/INFO]: Saving chunks for level 'world'/CONTROL

**Comment by xJon** [comment]
In that log you gave me we can see few errors about the server failing to load the banlist and whitelist but that's not a crash report.

**Comment by jimmy06200** [comment]
Well ^^ sorry! i will explain a little bit more me
I have purchase on akliz server for playing with few people.
I try to download the 1.7.10 mod pack. it work for one day and put me for no reason the ''  Exception in thread "AE2 VersionChecker" ''.
So i try to find the log but nothing about crash or what ever so try to reboot everything redownload the mod  pack by the serv but still nothing. Just this version checker on the console.
So bad to be a noob and don't anderstand a thing ... so i will try again and again thx for helping i will put the log if the serv want

**Comment by xJon** [comment]
But the server works okay? can you play?

**Comment by jimmy06200** [comment]
In ,y console i just have;


 Exception in thread "AE2 VersionChecker" 
> 

A big pain

**Comment by xJon** [comment]
What version of the modpack do you play with?

**Comment by jimmy06200** [comment]
0.8.2 version ^^ and i did what you tell me and it kinda work thx a lot.
now i will try it ^^

**Comment by xJon** [comment]
Closed due to inactivity.
